adeept:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_1
    pid: {p: 10.0, i: 0, d: 0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_2
    pid: {p: 10.0, i: 0, d: 0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_3
    pid: {p: 10.0, i: 0, d: 0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_4
    pid: {p: 10.0, i: 0, d: 0}

  # Velocity Controllers ---------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: Joint_1
    pid: {p: 10.0, i: 0, d: 0}
  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: Joint_2
    pid: {p: 10, i: 0, d: 0}
  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: Joint_3
    pid: {p: 10, i: 0, d: 0}
  joint4_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: Joint_4
    pid: {p: 10, i: 0, d: 0}
